version: '3'

services:
  netflixpg:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'netflixpg'
    restart: always
    volumes:
      - netflixpg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

volumes:
  netflixpg-data:
